image:
  - Visual Studio 2017

platform:
  - x64
  - x86

environment:
  RACKET_VERSION: 7.2
  CYGPATH: cygpath -u # used by download-racket.sh on Windows

############################################################################
# set PKG_DIR to be used test_scripts & artifacts
for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
          platform: x64

    environment:
      PKG_DIR: libgit2-win32-x86_64
        
  -
    matrix:
      only:
        - image: Visual Studio 2017
          platform: x86

    environment:
      PKG_DIR: libgit2-win32-i386
      
############################################################################
# get the src submodule
install:
  - git submodule init
  - git submodule update

############################################################################
# os-specific commands to install Racket & install package for testing
for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
        
    before_build:
      - git clone https://github.com/liberalartist/appveyor-racket.git C:\a-r
      - bash C:\a-r\download-racket.sh C:\install-racket.exe
      - C:\install-racket.exe /S /D=C:\racket
      - set PATH=%PATH%;C:\racket\

    before_test:
      - raco pkg install -i --link %PKG_DIR%
      
  -
    matrix:
      only:
        - image: Ubuntu
        
    before_build:
      - echo todo
      - exit 1

    before_test:
      - raco pkg install -i --link "$PKG_DIR"

############################################################################
# build libgit2
build_script:
  - racket make-libgit2.rkt

# test that the package works
test_script:
  - racket test-script.rkt

# save the build package
artifacts:
  - path: $(PKG_DIR)

