image:
  - Visual Studio 2017

platform:
  - x64
  - x86

environment:
  RACKET_VERSION: 7.2
  CYGPATH: cygpath -u # used by download-racket.sh on Windows

############################################################################
# set PKG_DIR to be used test_scripts & artifacts
for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
          platform: x64

    environment:
      PKG_DIR: libgit2-win32-x86_64
        
  -
    matrix:
      only:
        - image: Visual Studio 2017
          platform: x86

    environment:
      PKG_DIR: libgit2-win32-i386
      
############################################################################
# get the src submodule
install:
  - git submodule init
  - git submodule update

# install Racket
before_build:
  - git clone https://github.com/liberalartist/appveyor-racket.git C:\a-r
  - bash C:\a-r\download-racket.sh C:\install-racket.exe
  - C:\install-racket.exe /S /D=C:\racket
  - set PATH=%PATH%;C:\racket\

# build libgit2
build_script:
  - racket make-libgit2.rkt

test_script:
  - cd $(PKG_DIR)
  - raco pkg install -i
  - racket ../test-script.rkt

artifacts:
  - path: $(PKG_DIR)

